stages:          # List of stages for jobs, and their order of execution
  - build
  - verify
  - test
  - pages

build:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - echo "Building project"
    - mvn clean compile

lint:
  stage: verify
  only:
    - master
    - merge_requests
  script:
    - echo "Checking formatting"
    - mvn clean formatter:validate

test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - echo "Running tests"
    - mvn clean test

pages:
  stage: pages
  script:
    - echo "Building Javadoc"
    - mvn javadoc:javadoc
  artifacts:
    paths:
      - public/javadoc
  only:
    - master